### ISSUE TITLE
Add outlet states to session.data and OCS Feed in SynaccessAgent

### ISSUE THREAD

**Issue by BrianJKoopman** [simonsobs/socs#115]
As discussed in #103, we should add the outlet state to the `session.data` of Tasks that change it. Additionally we should publish the outlet state to a single OCS Feed when changed. This will record the outlet states in the housekeeping .g3 files.

**Comment by JakeSpisak** [comment]
Add to this update: include a way in the agent config to designate 'protected' channels that issue a warning message when you try to turn them off. This will prevent accidentally turning off critical components

**Comment by BrianJKoopman** [comment]
Resolved by #183.
