### ISSUE TITLE
Archive SMuRF's noise plots as well?

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/socs#141]
When I run `S.take_noise_psd()` we get two folders in the archived smurf data. `ctime_take_stream_data/` and `ctime_None/` There are outputs in both but we don't see any of the plots that are generated. (I'd love to get the histograms saved). 

Any chance we can add this?

**Comment by jlashner** [comment]
Yep! Thanks for letting me know, just submitted a PR to pysmurf here: https://github.com/slaclab/pysmurf/pull/604.

**Comment by jlashner** [comment]
Closing this because the PR's been merged, but will not that people on the main branch may not see them until the find-freq-eta-scan-speedup branch is merged into main.
