### ISSUE TITLE
Experiment with SNMP

### ISSUE THREAD

**Issue by mhasself** [simonsobs/socs#30]
At some point we will want Agents that speak SNMP to some hardware devices.  It would be useful to take a few steps in that direction, perhaps with a simple ibootbar control agent.

SNMP is the best way to communicate with:
- remote power switches such as ibootbars
- UPSes such as Eaton UPSes

UPS and ibootbar communication over SNMP has been implemented for ACT; that code can be extracted and shared.

A cursory reading of http://snmplabs.com/pysnmp/examples/v3arch/twisted/contents.html suggests that twisted + SNMP is going to work great.

**Comment by BrianJKoopman** [comment]
SNMP support added by #101, closing.
