### ISSUE TITLE
ibootbar -- lock some outlets

### ISSUE THREAD

**Issue by mhasself** [simonsobs/socs#417]
Can we add an option to annotate outlets in the ibootbar/synaccess agent so that they can be treated slightly differently (especially by ocs-web)?  The goal is to make it a bit difficult for someone to power off critical network infrastructure remotely (leading to an unrecoverable outage).  This could be a passive notation (the Agent simply provides information about what outlets are critical to network) or explicit prevention (the Agent provides that information but also rejects state change requests on those outlets) -- for ocs-web it's pretty much the same.

I'm imagining either a config file or simply cmdline args like "--lock-outlet login2-1 --lock-outlet switch3".  The config file might be desirable in the longer term, when we start having "access levels" and the ability to escalate privileges.  But cmdline args would be great for now.

**Comment by davidvng** [comment]
Should there then also be a way to unlock an outlet if needed? If there is only a lock outlet option I think the only way to unlock is if the agent is re-initialized?

**Comment by mhasself** [comment]
Ya, I think that's a reasonable thing to build in.  One solution might be to have a task that lets you lock/unlock outlets.

When "Access Levels" are implemented, that task could be restricted to more privileged users.
