### ISSUE TITLE
OCS pysmurf controller fails if passed non-string arguments

### ISSUE THREAD

**Issue by jlashner** [simonsobs/socs#42]
Passing a list of arguments that aren't strings to ocs-pysmurf-controller's run task breaks it in such a way that you have to restart the agent before running another script.

**Comment by BrianJKoopman** [comment]
Is this still a problem? It looks like it might have been resolved in #54, specifically in 1e08b7d708ff9dd778964fed912f03f91b4f08bb, with what is now line 162: https://github.com/simonsobs/socs/blob/5798dcf1e7c3f86eb726905460bbf193f3feb03d/agents/pysmurf_controller/pysmurf_controller.py#L162

**Comment by jlashner** [comment]
Yeah I think we can close this.
