### ISSUE TITLE
rename the timestream aggregator

### ISSUE THREAD

**Issue by BrianJKoopman** [simonsobs/socs#49]
@mhasself points out that "timestream-aggregator" is perhaps too general/not quite accurate. We should think of a better name for this agent. Please brainstorm ideas here.

**Comment by mhasself** [comment]
We're using "smurf-*" for various detector system things.  How about smurf-catcher?  I am approximately half serious.

**Comment by BrianJKoopman** [comment]
I like the "smurf-" prefix idea.

Throwing out some ideas:
* "smurf-writer", since it's ultimately a G3Writer
* "smurf-stream-recorder", since it records data from the "smurf-streamer"
* "smurf-stream-writer", a combination of the two above suggestions

**Comment by jlashner** [comment]
I honestly like "smurf-catcher" or "smurf-recorder". I think "smurf-stream-catcher" and "smurf-stream-recorder" are more clear, but that's getting a bit long (note that instance id's will probably also have the "c1s2" suffix for the crate and slot numbers).

**Comment by BrianJKoopman** [comment]
Alright, I'll rename it to "smurf-recorder" unless there are objections. #46 and #50 should be wrapped up first.
