### ISSUE TITLE
LS372 Custom PID needs to check mode

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/socs#577]
I accidentally set the heater output to power through OCS-web while turning the heater to zero. (I didn't know which mode to use but wasn't worried because it was zero either way). 

The I tried to restart the PID, which was now trying to operate in power mode instead of current mode and that didn't go well (luckily it was trying to set powers well beyond the boxes abilities so it just didn't do anything). 

The custom PID initialization should check that the heater output mode is current before beginning.

**Comment by BrianJKoopman** [comment]
Yeah, if the custom PID always wants current mode it should probably just set it to current mode before doing anything.

Also, the "Display" argument in `set_heater_output` is optional. If not provided, it will stay on whatever setting it is currently on. This isn't clear in ocs-web though.
