### ISSUE TITLE
Issue with pysmurf-controller publishing infs

### ISSUE THREAD

**Issue by jlashner** [simonsobs/socs#645]
I think in both SATp1 and SATp3 we've seen the following error in the schedule, caused by a pysmurf-controller:
```
ocs.client_http.ControlClientError: [0, 0, 0, 0, 'wamp.error.runtime_error', ['Session.data cannot store inf/-inf; please convert to NaN.'], {}]
```

(I wish there were a better way to copy logs from loki...)
<img width="1207" alt="image" src="https://github.com/simonsobs/socs/assets/4718487/14ec4d2d-8beb-47a0-ab14-45df15e09587">

This happens immediately after try to return from the bias step task:
<img width="1215" alt="image" src="https://github.com/simonsobs/socs/assets/4718487/f1cdeefb-6631-4796-9449-d0cf02f48b56">

There must be an `inf` showing up in the quantiles here somehow:
https://github.com/simonsobs/socs/blob/6d3a2c28d1b41f632d9fced088c19f90757952d4/socs/agents/pysmurf_controller/agent.py#L804

We should figure out whatever masking we need to do to this array to stop this from happening.

**Comment by BrianJKoopman** [comment]
> (I wish there were a better way to copy logs from loki...)

If you find the log segment you want there's a download button to download the logs as a text file. (Still not the most convenient thing, but perhaps better?)
