### ISSUE TITLE
Need a new socs build for dependency bump

### ISSUE THREAD

**Issue by mhasself** [simonsobs/socs#648]
I just had to fix something in soaculib that prevents LAT motion.

https://github.com/simonsobs/soaculib/pull/30

So we need a new socs image.  If that doesn't happen naturally, soon, we can trigger one with an empty commit.  Let me know.  (Current main head is https://github.com/simonsobs/socs/commit/1b8b8227fac2bc26e36497ea7b9a34dbb9fee996.)

**Comment by BrianJKoopman** [comment]
#649 will be merged imminently, will respond here when builds complete.

**Comment by BrianJKoopman** [comment]
Image `simonsobs/socs:v0.4.5-22-gf2e0e38-dev` is fresh and should have the required aculib updates.
