### ISSUE TITLE
Warm Thermometry Readout Through Labjack

### ISSUE THREAD

**Issue by JakeSpisak** [simonsobs/socs#68]

**Comment by BrianJKoopman** [comment]
Did work in #75 satisfy this requirement? Thinking specifically of the `warm_therm` [function](https://github.com/simonsobs/socs/blob/71a8640d208099bd767ba7f0e7430b6741b0b16d/agents/labjack/labjack_agent.py#L112) in there.

**Comment by JakeSpisak** [comment]
Theoretically yes, though I haven't closed the issue since it hasn't actually been tested on the warm thermometery system. (Waiting on Sam to set it up at Yale).  I'm also not entirely sure what modifications are needed with the additional mux80 device we will be using
